In [1]:
import pandas as pd
import numpy as np

In [2]:
emails = pd.read_csv('emails.csv')

In [8]:
emails[emails.spam == 0]

text  spam
1368  Subject: hello guys ,  i ' m " bugging you " f...     0
1369  Subject: sacramento weather station  fyi  - - ...     0
1370  Subject: from the enron india newsdesk - jan 1...     0
1371  Subject: re : powerisk 2001 - your invitation ...     0
1372  Subject: re : resco database and customer capt...     0
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[4360 rows x 2 columns]

In [13]:
#emails.iloc[1368,0]

In [10]:
emails.shape

(5728, 2)

In [11]:
emails.spam.value_counts()/emails.shape[0]*100

0    76.117318
1    23.882682
Name: spam, dtype: float64

In [24]:
emails['text'] = emails['text'].apply(lambda x: x.replace('Subject:',''))
emails['text'] = emails['text'].apply(lambda x: x.replace('subject:',''))
emails['text'] = emails['text'].apply(lambda x: x.replace('Subject',''))
emails['text'] = emails['text'].apply(lambda x: x.replace('subject',''))


In [25]:
def process_text(text):
    import re
    
    return re.sub(r'\d',"",text)

In [26]:
process_text('This is so good 12345 and here it is 4949')

'This is so good  and here it is '

In [27]:
emails['text'] = emails['text'].apply(lambda x: process_text(x))

In [119]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [120]:
matrix = TfidfVectorizer(lowercase=True, 
                         stop_words='english', 
                         min_df = 0.2,
                         ngram_range=(1,2)
                         ,max_df=0.95
                        )

In [121]:
X = matrix.fit_transform(emails['text']).toarray()

In [122]:
X[0:5]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.34239878, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.93955472, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.3794312 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.92521996, 0.        ,
        0.        , 0.        , 0.        , 0

In [123]:
matrix.get_feature_names_out()

array(['cc', 'com', 'ect', 'ect ect', 'enron', 'group', 'hou', 'hou ect',
       'information', 'kaminski', 'know', 'let', 'like', 'need', 'pm',
       'research', 'thanks', 'time', 'vince', 'vince kaminski'],
      dtype=object)

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    emails['spam'], 
                                                    train_size = 0.8, 
                                                    random_state = 12345)

In [126]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [127]:
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [128]:
pred = tree_model.predict(X_test)

In [129]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [130]:
confusion_matrix(y_pred = pred, y_true=y_test)

array([[771,  81],
       [ 28, 266]])

In [131]:
accuracy_score(y_pred = pred, y_true=y_test)

0.9048865619546248

In [132]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [133]:
pred = rf_model.predict(X_test)

In [134]:
confusion_matrix(y_pred = pred, y_true=y_test)

array([[772,  80],
       [ 19, 275]])

In [135]:
accuracy_score(y_pred = pred, y_true=y_test)

0.9136125654450262